name: xylophone
description: A Flutter project to play xylophone.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/xyloNote1.wav
    - assets/sounds/xyloNote2.wav
    - assets/sounds/xyloNote3.wav
    - assets/sounds/xyloNote4.wav
    - assets/sounds/xyloNote5.wav
    - assets/sounds/xyloNote6.wav
    - assets/sounds/xyloNote7.wav
